// src/constants/errorCodes.js
module.exports = {
  // Authentication
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
  INVALID_TWO_FACTOR_CODE: 'INVALID_TWO_FACTOR_CODE',
  INVALID_RECOVERY_CODE: 'INVALID_RECOVERY_CODE',
  RECOVERY_CODE_USED: 'RECOVERY_CODE_USED',

  // CSRF & Security
  INVALID_CSRF_TOKEN: 'INVALID_CSRF_TOKEN',
  RATE_LIMITED: 'RATE_LIMITED',
  CAPTCHA_REQUIRED: 'CAPTCHA_REQUIRED',
  INVALID_CAPTCHA: 'INVALID_CAPTCHA',
  EMAIL_CODE_REQUIRED: 'EMAIL_CODE_REQUIRED',
  INVALID_EMAIL_CODE: 'INVALID_EMAIL_CODE',

  // File Operations
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  FILE_IN_TRASH: 'FILE_IN_TRASH',
  FILE_NOT_IN_TRASH: 'FILE_NOT_IN_TRASH',

  // Share Operations
  SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
  SHARE_EXPIRED: 'SHARE_EXPIRED',
  SHARE_PASSWORD_REQUIRED: 'SHARE_PASSWORD_REQUIRED',
  SHARE_PASSWORD_INCORRECT: 'SHARE_PASSWORD_INCORRECT',
  SHARE_DOWNLOAD_LIMIT_REACHED: 'SHARE_DOWNLOAD_LIMIT_REACHED',

  // Admin Operations
  ADMIN_REQUIRED: 'ADMIN_REQUIRED',

  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
